image: cypress/base

stages:
  - install
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"


install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/
      - cache/Cypress

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - install

test:
  stage: test
  dependencies:
    - build
    - install
  script:
    - npm run cy:ci
  artifacts:
    when: on_failure
    expire_in: '1 week'
    untracked: true
    paths:
      - cypress/videos
      - cypress/screenshots
