build:
  image: node:lts-alpine
  stage: build
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/
      - build

test:e2e:
  stage: test
  image: cypress/base:10
  dependencies:
    - build
  script:
    - npm run cy:ci
  artifacts:
    when: on_failure
    expire_in: '1 week'
    untracked: true
    paths:
      - cypress/videos
      - cypress/screenshots
