image: cypress/base:12.14.0

stages:
  - install
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install:
  stage: install
  script:
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
    - npm run cy:verify

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 60 mins

.test:electron:
  stage: test
  dependencies:
    - build
  script:
    - npm run serve &
    - npm run cy:ci
  artifacts:
    when: on_failure
    expire_in: '1 week'
    untracked: true
    paths:
      - cypress/videos
      - cypress/screenshots

test:chrome:
  stage: test
  image: cypress/browsers:node12.13.0-chrome78-ff70
  dependencies:
    - build
  script:
    - npm run serve &
    - npm run cy:ci:chrome
  artifacts:
    when: on_failure
    expire_in: '1 week'
    untracked: true
    paths:
      - cypress/videos
      - cypress/screenshots

electrons-1:
  extends: .test:electron
electrons-2:
  extends: .test:electron
electrons-3:
  extends: .test:electron